In [1]:
import pandas as pd

In [2]:
teams = pd.read_csv("teams.csv")

In [3]:
teams.describe()

,LEAGUE_ID,TEAM_ID,MIN_YEAR,MAX_YEAR,YEARFOUNDED,ARENACAPACITY
count,30.0,3.000000e+01,30.000000,30.0,30.000000,26.000000
mean,0.0,1.610613e+09,1969.700000,2019.0,1969.700000,18553.307692
std,0.0,8.803408e+00,16.698441,0.0,16.698441,3916.923362
min,0.0,1.610613e+09,1946.000000,2019.0,1946.000000,0.000000
25%,0.0,1.610613e+09,1952.000000,2019.0,1952.000000,18641.500000
50%,0.0,1.610613e+09,1970.000000,2019.0,1970.000000,19131.000000
75%,0.0,1.610613e+09,1979.000000,2019.0,1979.000000,19790.750000
max,0.0,1.610613e+09,2002.000000,2019.0,2002.000000,21711.000000

In [5]:
teams.shape

(30, 14)

In [6]:
teams.isnull().sum()

LEAGUE_ID             0
TEAM_ID               0
MIN_YEAR              0
MAX_YEAR              0
ABBREVIATION          0
NICKNAME              0
YEARFOUNDED           0
CITY                  0
ARENA                 0
ARENACAPACITY         4
OWNER                 0
GENERALMANAGER        0
HEADCOACH             0
DLEAGUEAFFILIATION    0
dtype: int64

In [7]:
teams.columns

Index(['LEAGUE_ID', 'TEAM_ID', 'MIN_YEAR', 'MAX_YEAR', 'ABBREVIATION',
       'NICKNAME', 'YEARFOUNDED', 'CITY', 'ARENA', 'ARENACAPACITY', 'OWNER',
       'GENERALMANAGER', 'HEADCOACH', 'DLEAGUEAFFILIATION'],
      dtype='object')

In [8]:
teams = teams[
    ["TEAM_ID", "ABBREVIATION", "NICKNAME", "CITY", "YEARFOUNDED"]
]
teams.head()

      TEAM_ID ABBREVIATION   NICKNAME         CITY  YEARFOUNDED
0  1610612737          ATL      Hawks      Atlanta         1949
1  1610612738          BOS    Celtics       Boston         1946
2  1610612740          NOP   Pelicans  New Orleans         2002
3  1610612741          CHI      Bulls      Chicago         1966
4  1610612742          DAL  Mavericks       Dallas         1980

In [10]:
teams["CITY"] = teams["CITY"].str.title()
teams["NICKNAME"] = teams["NICKNAME"].str.title()
teams["ABBREVIATION"] = teams["ABBREVIATION"].str.upper()
teams.head()

      TEAM_ID ABBREVIATION   NICKNAME         CITY  YEARFOUNDED
0  1610612737          ATL      Hawks      Atlanta         1949
1  1610612738          BOS    Celtics       Boston         1946
2  1610612740          NOP   Pelicans  New Orleans         2002
3  1610612741          CHI      Bulls      Chicago         1966
4  1610612742          DAL  Mavericks       Dallas         1980

In [11]:
teams = teams.rename(columns={
    "TEAM_ID": "team_id",
    "ABBREVIATION": "abbreviation",
    "NICKNAME": "team_name",
    "CITY": "city",
    "YEARFOUNDED": "year_founded"
})
teams.columns

Index(['team_id', 'abbreviation', 'team_name', 'city', 'year_founded'], dtype='object')

In [12]:
from sqlalchemy import create_engine
engine = create_engine(
    "postgresql+psycopg2://postgres:"password"@localhost:"portnumber"/nba_analysis"
)
teams.to_sql(
    "teams",
    engine,
    if_exists="replace",   # use replace ONLY if table doesn't exist
    index=False
)

30